import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppNextUI from "./nextUI/AppNextUI";
import { Container } from "./components/layout/container/Index";
import { Toaster } from "react-hot-toast";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
      <StoreProvider>
        <AppNextUI>
          <Toaster />
          <Container>{children}</Container>
        </AppNextUI>
        </StoreProvider>
      </body>
    </html>
  );
}
